<a href="https://colab.research.google.com/github/juangui96/DS-_-Boot-Camp/blob/main/Avance_Proyecto_V.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#SUPER STORE - PREDICCION Y ANALISIS
Objetivo: Predecir cuales seran las ventas en los proximos periodos de tiempo de los clientes, zonas y categoria de productos que se tiene en el
momento partiendo de una definicion de estado actual de las ventas.

#Cargue Librerias

In [ ]:
#importar librerias
import pandas as pd
import numpy as np

In [ ]:
#ignorar warning

import warnings
warnings.filterwarnings("ignore")

In [ ]:
#sql alchquemy
from sqlalchemy import create_engine, text

#CONEXION CON POSTGRE
A pesar que la conexion con posgre no se logra desde colab debido a que la maquina virtual que se utiliza no coinicide con la IP local en donde se encuentra instalado el programa, se deja el codigo sobre como puede funcionar si se trabajara en otros ambientes.
Con el fin de cumplir el objetivo de esta entrega, mas adelante se carga la base y se utiliza SQL Alchemy para realizar algunas consultas.

Lo primero que se debe hacer es cargar las variables: Hotname, database, username, pwd y port_id con los datos reales de postgre. Posteriormente, se crea el engine y se genera la conexion para luego crear las querys. En este punto es donde falla la conexion con colab, por lo explicado anteriormente de las IPs.

In [ ]:
#parametros
#Traidos desde postgre ya con las bases cargadas

hostname = 'localhost'
database='Call Center'
username = 'postgres'
pwd='040396$'
port_id='5432'

In [ ]:
engine= create_engine(f"postgresql://{username}:{pwd}@localhost:{port_id}/{database}")
engine

Engine(postgresql://postgres:***@localhost:5432/Call Center)

In [ ]:
from sqlalchemy import text
def runQuery(sql):
    result = engine.connect().execute((text(sql)))
    return pd.DataFrame(result.fetchall(), columns=result.keys())

In [ ]:
query="""
SELECT * FROM customers
"""
runQuery(query)

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

#CARGAR DATOS Y CONEXION SQL ALCHEMY

In [ ]:
url = 'https://raw.githubusercontent.com/juangui96/DS-_-Boot-Camp/main/Proyecto_Final/Actividad_1/super%20Store%20.csv'
ss = pd.read_csv(url, sep = ';')
ss['Order Date']=pd.to_datetime(ss['Order Date'],format='%d/%m/%Y')
ss['Mes']=ss['Order Date'].dt.month
ss.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Mes
0,1,CA-2017-152156,2017-11-08,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,11
1,2,CA-2017-152156,2017-11-08,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,11
2,3,CA-2017-138688,2017-06-12,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,6
3,4,US-2016-108966,2016-10-11,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,9.575.775,10
4,5,US-2016-108966,2016-10-11,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,10

##Crear engine

In [ ]:
ruta = './'
engine=create_engine('sqlite://')

## Funcion para correr querys

In [ ]:
df = ss.to_sql('ss',engine, if_exists='replace',index= False)

In [ ]:
def runQuery(sql):
  result = engine.connect().execute((text(sql)))
  return pd.DataFrame(result.fetchall(),columns=result.keys())

##Query Prueba

In [ ]:
query_ejemplo= """
SELECT * FROM ss
LIMIT 5
"""
ej1 = runQuery(query_ejemplo)
ej1

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Mes
0,1,CA-2017-152156,2017-11-08 00:00:00.000000,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,11
1,2,CA-2017-152156,2017-11-08 00:00:00.000000,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,11
2,3,CA-2017-138688,2017-06-12 00:00:00.000000,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,6
3,4,US-2016-108966,2016-10-11 00:00:00.000000,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,9.575.775,10
4,5,US-2016-108966,2016-10-11 00:00:00.000000,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,10

Crear un DF alterno a SS para convertir las ventas a millones, retirando el punto y luego dividiendo entre un millon. Este tratamiento es el mismo que se ha trabajado en el procesamiento del EDA.

In [ ]:
query_ejemplo= """
SELECT *,
  (CAST(REPLACE(sales, '.', '') AS FLOAT)/1000000) AS sales2,
  strftime('%d/%m/%Y', "Order Date") AS Fecha2,
  strftime('%Y', "Order Date") AS AÑO
FROM ss
WHERE
  (CAST(REPLACE(sales, '.', '') AS FLOAT)/1000000) is not null
"""
ss1 = runQuery(query_ejemplo)
df = ss1.to_sql('ss1',engine, if_exists='replace',index= False)
ss1

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Mes,sales2,Fecha2,AÑO
0,1,CA-2017-152156,2017-11-08 00:00:00.000000,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,11,0.026196,08/11/2017,2017
1,2,CA-2017-152156,2017-11-08 00:00:00.000000,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,11,0.073194,08/11/2017,2017
2,3,CA-2017-138688,2017-06-12 00:00:00.000000,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,6,0.001462,12/06/2017,2017
3,4,US-2016-108966,2016-10-11 00:00:00.000000,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,9.575.775,10,9.575775,11/10/2016,2016
4,5,US-2016-108966,2016-10-11 00:00:00.000000,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,10,0.022368,11/10/2016,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9789,9796,CA-2017-125920,2017-05-21 00:00:00.000000,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,...,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798,5,0.003798,21/05/2017,2017
9790,9797,CA-2016-128608,2016-01-12 00:00:00.000000,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368,1,0.010368,12/01/2016,2016
9791,9798,CA-2016-128608,2016-01-12 00:00:00.000000,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188,1,0.235188,12/01/2016,2016
9792,9799,CA-2016-128608,2016-01-12 00:00:00.000000,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376,1,0.026376,12/01/2016,2016
9793,9800,CA-2016-128608,2016-01-12 00:00:00.000000,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384,1,0.010384,12/01/2016,2016

## GRUPO QUERY 1: Cual es la tasa de ventas por mes y cuales son los meses que tienen una mayor venta por dia?
Segun la query que se muestra a continuacion, se puede ver que el mes de septiembre, octubre, noviembre y diciembre son los que mejor comportamiento presenta en cuanto a ventas/dia. Asi mismo, el año 2017 y 2018 son los que tienen un valor mas alto en cuanto a esta tasa, esto se puede apreciar en la segunda query.

In [ ]:
query_tasaventas = """
WITH Ventas_mes as
(SELECT
    AÑO, Mes, CAST(sales2 as FLOAT) AS Ventas_miles,
    CASE
      WHEN Mes in (1,3,5,7,8,10,12) THEN 31
      WHEN Mes in (4,6,9,11) THEN 30
      ELSE CAST('28' as FLOAT)
    END AS Dias_mes
FROM ss1)
SELECT AÑO,Mes, sum(Ventas_miles), Dias_mes, (sum(Ventas_miles)/Dias_mes) as Tasa
FROM Ventas_mes
GROUP BY AÑO,Mes
ORDER BY Tasa Desc
"""
tasa_ventas = runQuery(query_tasaventas)
tasa_ventas

     AÑO  Mes  sum(Ventas_miles)  Dias_mes      Tasa
0   2017    9          67.526914      30.0  2.250897
1   2018   11          54.670693      30.0  1.822356
2   2017   11          48.484917      30.0  1.616164
3   2018    9          41.607379      30.0  1.386913
4   2015    9          40.800209      30.0  1.360007
5   2018   10          40.639645      31.0  1.310956
6   2016   11          37.387277      30.0  1.246243
7   2015   11          35.405410      30.0  1.180180
8   2018    8          36.287362      31.0  1.170560
9   2018    6          33.669225      30.0  1.122308
10  2017   12          34.466545      31.0  1.111824
11  2018   12          33.417914      31.0  1.077997
12  2015   12          33.259735      31.0  1.072895
13  2016   12          32.117162      31.0  1.036037
14  2018    4          25.183721      30.0  0.839457
15  2017    8          25.978069      31.0  0.838002
16  2017    5          24.677478      31.0  0.796048
17  2018    5          23.455978      31.0  0.756644
18  2016    1          23.146257      31.0  0.746653
19  2016    9          22.122442      30.0  0.737415
20  2016   10          22.172743      31.0  0.715250
21  2016    3          22.158954      31.0  0.714805
22  2017    3          22.019279      31.0  0.710299
23  2018    3          19.744470      31.0  0.636918
24  2015    3          19.553701      31.0  0.630765
25  2016    5          19.534169      31.0  0.630134
26  2015    6          18.025561      30.0  0.600852
27  2017    4          17.926001      30.0  0.597533
28  2016    8          18.445663      31.0  0.595021
29  2017    6          17.071144      30.0  0.569038
30  2017   10          17.187444      31.0  0.554434
31  2016    4          16.496905      30.0  0.549897
32  2018    1          16.985532      31.0  0.547920
33  2015    7          16.773109      31.0  0.541068
34  2018    7          16.644628      31.0  0.536923
35  2017    7          16.162774      31.0  0.521380
36  2016    6          13.603731      30.0  0.453458
37  2015    8          14.016061      31.0  0.452131
38  2015   10          14.000386      31.0  0.451625
39  2016    7          12.071722      31.0  0.389410
40  2018    2           9.154040      28.0  0.326930
41  2015    5           9.345661      31.0  0.301473
42  2015    4           8.776050      30.0  0.292535
43  2017    1           8.077210      31.0  0.260555
44  2017    2           5.959311      28.0  0.212833
45  2016    2           3.470585      28.0  0.123949
46  2015    1           2.882798      31.0  0.092993
47  2015    2           0.799427      28.0  0.028551

In [ ]:
query_tasaventas = """
WITH Ventas_mes as
(SELECT
    AÑO, Mes, CAST(sales2 as FLOAT) AS Ventas_miles,
    CASE
      WHEN Mes in (1,3,5,7,8,10,12) THEN 31
      WHEN Mes in (4,6,9,11) THEN 30
      ELSE CAST('28' as FLOAT)
    END AS Dias_mes
FROM ss1)
SELECT AÑO, sum(Ventas_miles), Dias_mes, (sum(Ventas_miles)/Dias_mes) as Tasa
FROM Ventas_mes
GROUP BY AÑO
ORDER BY Tasa Desc
"""
tasa_ventas = runQuery(query_tasaventas)
tasa_ventas

    AÑO  sum(Ventas_miles)  Dias_mes       Tasa
0  2018         351.460587        30  11.715353
1  2017         305.537086        30  10.184570
2  2016         242.727610        31   7.829923
3  2015         213.638108        30   7.121270

## GRUPO DE QUERY 2: Cuales son los clientes que estan por encima del promedio de ventas (de cada año) y en que ciudad se encuentran?
En todo el analisis de todos los años los clientes que tienen uno o mas meses de ventas por encima del promedio se encuentran en la query que se desarrolla a continuacion. Los clientes que compran mas recurrentemente por encima del promedio son: Zuschuss Carroll	 y Adrian Barton.
Es importante resaltar que, el año  2018 fue en el que hubo mas clientes con ventas por encima de promedio, asi mismo, se puede ver que las ciudades con mejor comportamiento de ventas son: philadelphia, NY, Y LA.
Por ultimo,al revisar las compras por encima del promedio a nivel general por cliente y region, se encuentra que Adam Shillingsburg	es el usuario que mas compra por encima del promedio en NY. Se puede entonces pensar que Zuschuss Carroll, compra en diferentes sitios pero por encima del promedio y que, Adam Shillingsburg, solo compra en NY.

In [ ]:
query_ventasregion1 = """
WITH vta_clt AS (
  SELECT AÑO, "Customer Name", State, City, SUM(Sales2) AS total_sales
  FROM ss1
  GROUP BY AÑO, "Customer Name", State, City
),
prom_vta AS (
  SELECT AÑO, AVG(Sales2) AS avg_sales
  FROM ss1
  GROUP BY AÑO
),
join_vtas AS (
  SELECT v.*, p.avg_sales
  FROM vta_clt v
  LEFT JOIN prom_vta p ON p.AÑO = v.AÑO
),
vtas_final AS (
SELECT *, CASE
  WHEN total_sales >= avg_sales THEN "Encima Prom"
  ELSE "Debajo prom"
  END AS Comparacion
FROM join_vtas
WHERE Comparacion = 'Encima Prom')
SELECT "Customer name", AÑO,  state, city, count(Comparacion)
FROM vtas_final
GROUP BY "Customer Name", AÑO, comparacion
ORDER BY count(Comparacion) DESC
"""
ventas_region = runQuery(query_ventasregion1)
ventas_region

         Customer Name   AÑO         State         City  count(Comparacion)
0        Cynthia Voltz  2018    California  Los Angeles                   4
1           Joe Elijah  2017      Colorado   Broomfield                   4
2            Adam Hart  2018  Pennsylvania      Chester                   3
3        Adrian Barton  2018       Arizona      Phoenix                   3
4       Anthony Rawles  2018    California      Concord                   3
...                ...   ...           ...          ...                 ...
1165     William Brown  2018    California  Los Angeles                   1
1166      Xylona Preis  2018         Texas     Pasadena                   1
1167    Yoseph Carroll  2015      Delaware       Newark                   1
1168  Zuschuss Carroll  2015    Washington      Edmonds                   1
1169  Zuschuss Carroll  2018         Texas      Houston                   1

[1170 rows x 5 columns]

In [ ]:
query_ventasregion2 = """
WITH vta_clt AS (
  SELECT AÑO, "Customer Name", State, City, SUM(Sales2) AS total_sales
  FROM ss1
  GROUP BY AÑO, "Customer Name", State, City
),
prom_vta AS (
  SELECT AÑO, AVG(Sales2) AS avg_sales
  FROM ss1
  GROUP BY AÑO
),
join_vtas AS (
  SELECT v.*, p.avg_sales
  FROM vta_clt v
  LEFT JOIN prom_vta p ON p.AÑO = v.AÑO
),
vtas_final AS (
SELECT *, CASE
  WHEN total_sales >= avg_sales THEN "Encima Prom"
  ELSE "Debajo prom"
  END AS Comparacion
FROM join_vtas
WHERE Comparacion = 'Encima Prom')
SELECT AÑO, count(Comparacion) as Comparacion
FROM vtas_final
GROUP BY  AÑO, comparacion
ORDER BY count(Comparacion) DESC
"""
ventas_region = runQuery(query_ventasregion2)
ventas_region

    AÑO  Comparacion
0  2018          490
1  2017          373
2  2015          301
3  2016          296

In [ ]:
query_ventasregion3 = """
WITH vta_clt AS (
  SELECT AÑO, "Customer Name", State, City, SUM(Sales2) AS total_sales
  FROM ss1
  GROUP BY AÑO, "Customer Name", State, City
),
prom_vta AS (
  SELECT AÑO, AVG(Sales2) AS avg_sales
  FROM ss1
  GROUP BY AÑO
),
join_vtas AS (
  SELECT v.*, p.avg_sales
  FROM vta_clt v
  LEFT JOIN prom_vta p ON p.AÑO = v.AÑO
),
vtas_final AS (
SELECT *, CASE
  WHEN total_sales >= avg_sales THEN "Encima Prom"
  ELSE "Debajo prom"
  END AS Comparacion
FROM join_vtas
WHERE Comparacion = 'Encima Prom')
SELECT
State,City, count(Comparacion)
FROM vtas_final
GROUP BY State, City
ORDER BY count(comparacion) desc

"""
ventas_region = runQuery(query_ventasregion3)
ventas_region

             State           City  count(Comparacion)
0       California    Los Angeles                 120
1         New York  New York City                 118
2     Pennsylvania   Philadelphia                 106
3       California  San Francisco                  74
4            Texas        Houston                  67
..             ...            ...                 ...
339     Washington      Vancouver                   1
340  West Virginia       Wheeling                   1
341      Wisconsin       Appleton                   1
342      Wisconsin        Kenosha                   1
343        Wyoming       Cheyenne                   1

[344 rows x 3 columns]

In [ ]:
query_ventasregion4 = """
WITH vta_clt AS (
  SELECT AÑO, "Customer Name", State, City, SUM(Sales2) AS total_sales
  FROM ss1
  GROUP BY AÑO, "Customer Name", State, City
),
prom_vta AS (
  SELECT AÑO, AVG(Sales2) AS avg_sales
  FROM ss1
  GROUP BY AÑO
),
join_vtas AS (
  SELECT v.*, p.avg_sales
  FROM vta_clt v
  LEFT JOIN prom_vta p ON p.AÑO = v.AÑO
),
vtas_final AS (
SELECT *, CASE
  WHEN total_sales >= avg_sales THEN "Encima Prom"
  ELSE "Debajo prom"
  END AS Comparacion
FROM join_vtas
WHERE Comparacion = 'Encima Prom')
SELECT "Customer Name", count(Comparacion)
FROM vtas_final
GROUP BY "Customer Name"
ORDER BY count(Comparacion) desc
"""
ventas_region = runQuery(query_ventasregion4)
ventas_region

            Customer Name  count(Comparacion)
0        Zuschuss Carroll                   7
1           Adrian Barton                   7
2          Lena Creighton                   6
3           Kelly Lampkin                   6
4        Justin Deggeller                   6
..                    ...                 ...
647       Alejandro Grove                   1
648  Alejandro Ballentine                   1
649          Alan Shonely                   1
650            Alan Hwang                   1
651         Aaron Hawkins                   1

[652 rows x 2 columns]

In [ ]:
query_ventasregion5 = """
WITH vta_clt AS (
  SELECT AÑO, "Customer Name", State, City, SUM(Sales2) AS total_sales
  FROM ss1
  GROUP BY AÑO, "Customer Name", State, City
),
prom_vta AS (
  SELECT AÑO, AVG(Sales2) AS avg_sales
  FROM ss1
  GROUP BY AÑO
),
join_vtas AS (
  SELECT v.*, p.avg_sales
  FROM vta_clt v
  LEFT JOIN prom_vta p ON p.AÑO = v.AÑO
),
vtas_final AS (
SELECT *, CASE
  WHEN total_sales >= avg_sales THEN "Encima Prom"
  ELSE "Debajo prom"
  END AS Comparacion
FROM join_vtas
WHERE Comparacion = 'Encima Prom')
SELECT "Customer Name", State, City, count(Comparacion)
FROM vtas_final
GROUP BY "Customer Name", State, City
ORDER BY count(Comparacion) desc
"""
ventas_region = runQuery(query_ventasregion5)
ventas_region

## GRUPO DE QUERY 3: CUALES SON LAS CLASES DE PRODUCTOS (CATEGORY  Y SUBCATEGORY) FAVORITAS DE TODOS LOS ESTADOS Y DE LOS TRES ESTADOS CON MAYORES VENTAS?

Las categorias de productos con mayores ventas son Furniture, Technology y Office Supplies, a su vez, las subcategorias mas vendidas son: BookCases, Chairs, Phones. A nivel general, Texas marca la diferencia por sus grandes ventas en cuanto a bookcases, seguido de California en Chairs, Tables y Bookcases y por ultimo NY en cuanto a Chairs.  
Asi mismo se ha realizado un breve analisis del top 5 de los productos mas vendidos por año y por estado se resalta que:

1.   Se conserva la tendencia en cuanto las categorias y subcategorias, en estas ultimas se incluyen: Machine y Tables
2.   Los estados de California y Texas son los que aparecen en el top con mayor frecuencia, quiere decir que siempre estan en el top de los estados donde mas se vende.
3.  2015 y 2016 son los años en donde el producto que mas se vendio tiene unas ventas mayores, sin embargo y a pesar que en 2018 y 2017, el producto mas vendido no llega a unas cifras tan altos, los demas del top 5 si tienen valores mas altos, lo que explciaria porque las ventas se aumentan.

In [341]:
query_categorias = """
WITH prd_vta AS (
  SELECT  Category, "Sub-Category", SUM(Sales2) AS total_sales
  FROM ss1
  GROUP BY  Category, "Sub-Category"
)
SELECT *
FROM prd_vta
ORDER BY total_sales Desc
"""
vta_ctg = runQuery(query_categorias)
vta_ctg

           Category Sub-Category  total_sales
0         Furniture    Bookcases   198.019806
1         Furniture       Chairs   181.085736
2        Technology       Phones   160.430598
3         Furniture       Tables   136.495172
4   Office Supplies      Binders   102.579053
5   Office Supplies      Storage    64.148985
6        Technology      Copiers    63.044102
7        Technology     Machines    59.424089
8        Technology  Accessories    37.038489
9         Furniture  Furnishings    27.280390
10  Office Supplies   Appliances    25.730640
11  Office Supplies        Paper    23.149226
12  Office Supplies     Supplies    16.637778
13  Office Supplies          Art     8.559853
14  Office Supplies    Envelopes     5.760244
15  Office Supplies       Labels     2.913647
16  Office Supplies    Fasteners     1.065583

In [342]:
query_categorias2 = """
WITH prd_vta AS (
  SELECT  Category, "Sub-Category", State, SUM(Sales2) AS total_sales
  FROM ss1
  GROUP BY  Category, "Sub-Category", State
)
SELECT *
FROM prd_vta
WHERE state in (
                  SELECT State
                  FROM ss1
                  GROUP BY State
                  ORDER BY SUM(Sales2) desc
                  LIMIT 3
                  )
ORDER BY total_sales Desc
"""
vta_ctg = runQuery(query_categorias2)
vta_ctg

           Category Sub-Category       State  total_sales
0         Furniture    Bookcases       Texas   122.681180
1        Technology       Phones  California    49.963072
2         Furniture    Bookcases  California    47.520780
3         Furniture       Chairs  California    45.471610
4         Furniture       Tables  California    37.951357
5         Furniture       Chairs    New York    36.156798
6   Office Supplies      Binders    New York    27.730572
7   Office Supplies      Binders  California    18.549104
8        Technology       Phones       Texas    18.000294
9        Technology      Copiers    New York    17.199840
10       Technology     Machines       Texas    16.548225
11        Furniture    Bookcases    New York    16.099504
12       Technology      Copiers  California    15.519692
13        Furniture       Chairs       Texas    14.383411
14       Technology     Machines  California    13.309116
15        Furniture       Tables    New York    12.175515
16        Furniture       Tables       Texas    12.119387
17  Office Supplies      Storage       Texas    11.935988
18  Office Supplies      Binders       Texas     7.089220
19       Technology  Accessories       Texas     7.044196
20  Office Supplies        Paper       Texas     5.181820
21  Office Supplies     Supplies       Texas     4.363436
22       Technology       Phones    New York     4.335653
23  Office Supplies      Storage  California     4.077159
24       Technology     Machines    New York     3.291810
25       Technology  Accessories  California     3.231826
26  Office Supplies      Storage    New York     2.306192
27  Office Supplies    Envelopes       Texas     1.992942
28        Furniture  Furnishings       Texas     1.930573
29  Office Supplies   Appliances  California     1.820346
30  Office Supplies   Appliances       Texas     1.746224
31       Technology      Copiers       Texas     1.679944
32  Office Supplies          Art       Texas     1.590722
33        Furniture  Furnishings  California     1.563504
34  Office Supplies     Supplies  California     1.486258
35  Office Supplies        Paper  California     1.480649
36       Technology  Accessories    New York     1.392927
37  Office Supplies   Appliances    New York     1.008537
38        Furniture  Furnishings    New York     0.719138
39  Office Supplies        Paper    New York     0.646025
40  Office Supplies          Art  California     0.360228
41  Office Supplies       Labels       Texas     0.315310
42  Office Supplies          Art    New York     0.255525
43  Office Supplies    Envelopes  California     0.245434
44  Office Supplies    Fasteners       Texas     0.241348
45  Office Supplies       Labels  California     0.221800
46  Office Supplies     Supplies    New York     0.219299
47  Office Supplies    Envelopes    New York     0.161809
48  Office Supplies       Labels    New York     0.095064
49  Office Supplies    Fasteners  California     0.031150
50  Office Supplies    Fasteners    New York     0.028651

In [343]:
query_categorias3 = """
WITH prd_vta AS (
  SELECT  "Sub-Category", AÑO, State, SUM(Sales2) AS total_sales
  FROM ss1
  GROUP BY  "Sub-Category",AÑO, State
)
SELECT *
FROM prd_vta
WHERE state in (
                  SELECT State
                  FROM ss1
                  GROUP BY State
                  ORDER BY SUM(Sales2) desc
                  LIMIT 3
                  )
ORDER BY total_sales Desc
"""
vta_ctg = runQuery(query_categorias3)
vta_ctg

    Sub-Category   AÑO       State  total_sales
0      Bookcases  2017       Texas    45.682876
1      Bookcases  2016       Texas    43.421264
2      Bookcases  2018       Texas    27.961124
3         Phones  2017  California    17.627560
4      Bookcases  2018  California    17.024106
..           ...   ...         ...          ...
198    Fasteners  2016    New York     0.006113
199    Fasteners  2018  California     0.005464
200     Supplies  2015    New York     0.005103
201    Fasteners  2018    New York     0.004177
202    Fasteners  2015    New York     0.000968

[203 rows x 4 columns]

In [344]:
query_categorias3 = """
  SELECT * FROM (SELECT  Category, "Sub-Category", AÑO, State, SUM(Sales2) AS total_sales
  FROM ss1
  GROUP BY  Category, "Sub-Category",AÑO, State
  HAVING AÑO = '2015'
  ORDER BY SUM(Sales2) Desc
  LIMIT 5)
UNION ALL
  SELECT * FROM (SELECT  Category, "Sub-Category", AÑO, State, SUM(Sales2) AS total_sales
  FROM ss1
  GROUP BY  Category, "Sub-Category",AÑO, State
  HAVING AÑO = '2016'
  ORDER BY SUM(Sales2) Desc
  LIMIT 5)
UNION ALL
  SELECT * FROM (SELECT  Category, "Sub-Category", AÑO, State, SUM(Sales2) AS total_sales
  FROM ss1
  GROUP BY  Category, "Sub-Category",AÑO, State
  HAVING AÑO = '2017'
  ORDER BY SUM(Sales2) Desc
  LIMIT 5)
UNION ALL
  SELECT * FROM (SELECT  Category, "Sub-Category", AÑO, State, SUM(Sales2) AS total_sales
  FROM ss1
  GROUP BY  Category, "Sub-Category",AÑO, State
  HAVING AÑO = '2018'
  ORDER BY SUM(Sales2) Desc
  LIMIT 5)
"""
vta_ctg = runQuery(query_categorias3)
vta_ctg

      Category Sub-Category   AÑO       State  total_sales
0   Technology     Machines  2015       Texas    13.899936
1   Technology       Phones  2015  California    13.890920
2    Furniture       Tables  2015  California    10.250973
3    Furniture    Bookcases  2015  California     8.965647
4    Furniture       Chairs  2015    New York     7.710624
5    Furniture    Bookcases  2016       Texas    43.421264
6    Furniture       Tables  2016     Florida    15.245505
7    Furniture       Chairs  2016  California    12.265000
8    Furniture    Bookcases  2016  California     9.864964
9    Furniture       Chairs  2016    New York     8.071236
10   Furniture    Bookcases  2017       Texas    45.682876
11  Technology       Phones  2017  California    17.627560
12   Furniture       Chairs  2017  California    15.393882
13   Furniture       Tables  2017  California    13.730684
14   Furniture    Bookcases  2017  California    11.666063
15   Furniture    Bookcases  2018       Texas    27.961124
16   Furniture    Bookcases  2018  California    17.024106
17   Furniture       Chairs  2018  California    11.904844
18  Technology       Phones  2018  California    11.358554
19  Technology      Copiers  2018    New York    11.199968

## GRUPO QUERYS 4: Cuales son los clientes, estados y ciudades que han aumentado sus compras año a año

A partir de la siguiente Query se puede identificar que del total de 292 clientes unicamente 28 son los que tienen una variacion positiva en los años del analisis. Asi mismo se resalta que hay valores bastante grandes con una variacion de mas del 100%, en especial en los 4 clientes que se muestran en la segunda query, se resalta Ross Baird que tiene un aumento muy marcado durante los 2 primeros años (mas del 200%) y para el tercer año de mas del 100%.

Si se analiza la variacion positiva en ventas de los estados, se encuentra que unicamente hay 6 que presentan un crecimiento positivo: Pennsylvania, Illinois, North Carolinam, Michinga, Nebraska y Georgia, se resalta el comportamiento en ventas positivo de Georgia y Nebraska, teniendo este ultimo una variacion de mas del 300 entre el año 2 y 1.

Al revisar las ciudades, se confirma que los estados anteriormente mencionados son los que mayor variacion positiva presenta, al revisar la ciudad estas corresponden a: Aurora, Jackson,Detroit y Orlando esta ultima teniendo un crecimiento de mas del 100% por año,

In [364]:
query_varcliente = """
WITH vtas_2015 AS (
  SELECT  "Customer Name" as CN, SUM(Sales2) AS total_sales_2015
  FROM ss1
  WHERE AÑO = '2015'
  GROUP BY "Customer Name"
),
vtas_2016 AS (
  SELECT  "Customer Name" as CN, SUM(Sales2) AS total_sales_2016
  FROM ss1
  WHERE AÑO = '2016'
  GROUP BY "Customer Name"
),
vtas_2017 AS (
  SELECT "Customer Name" as CN, SUM(Sales2) AS total_sales_2017
  FROM ss1
  WHERE AÑO = '2017'
  GROUP BY "Customer Name"
),
vtas_2018 AS (
  SELECT "Customer Name" as CN, SUM(Sales2) AS total_sales_2018
  FROM ss1
  WHERE AÑO = '2018'
  GROUP BY "Customer Name"
),
vtas_final AS (
SELECT vtas_2015.CN, vtas_2015.total_sales_2015, vtas_2016.total_sales_2016, vtas_2017.total_sales_2017, vtas_2018.total_sales_2018
FROM vtas_2015
JOIN vtas_2016 ON vtas_2016.CN = vtas_2015.CN
JOIN vtas_2017 ON vtas_2017.CN = vtas_2015.CN
JOIN vtas_2018 ON vtas_2018.CN = vtas_2015.CN)

SELECT CN,
  ((total_sales_2016-total_sales_2015)/total_sales_2015) AS VARIACION_AÑO1,
  ((total_sales_2017-total_sales_2016)/total_sales_2016) AS VARIACION_AÑO2,
  ((total_sales_2018-total_sales_2017)/total_sales_2017) AS VARIACION_AÑO3
FROM vtas_final
WHERE
((total_sales_2016-total_sales_2015)/total_sales_2015)>0 AND
((total_sales_2017-total_sales_2016)/total_sales_2016)>0 AND
((total_sales_2018-total_sales_2017)/total_sales_2017) >0
ORDER BY VARIACION_AÑO1, VARIACION_AÑO2, VARIACION_AÑO3
"""
varcliente = runQuery(query_varcliente)
varcliente

                   CN  VARIACION_AÑO1  VARIACION_AÑO2  VARIACION_AÑO3
0          Jill Fjeld        0.035381        0.143944        0.452242
1       Jennifer Patt        0.049071        1.004834        7.499745
2       Corey Catlett        0.117698        0.287155        0.018118
3          Julie Kriz        0.118212        2.230536        0.030505
4        Duane Benoit        0.587995       13.940053        3.049031
5          Anne Pryor        0.686720        0.656360        2.075156
6    Dianna Vittorini        0.763797        1.364220        2.730562
7    Jennifer Braxton        1.287676        1.678168        0.307001
8         Alyssa Tate        1.979239        0.261905      205.798205
9      Kelly Andreada        2.401946        4.020996        0.988954
10   Michael Granlund        2.431204        3.082235        0.519152
11        Ken Brennan        2.457317        1.049971       10.295096
12     Pauline Webber        2.902525        0.676306        0.361033
13        Dean percer        3.284420        0.014702      119.698016
14     Pete Armstrong        3.930192        0.568142        0.620316
15          Adam Hart        4.762452      289.228391        0.680363
16     Anthony Rawles        5.000000      391.057099        1.879488
17       Frank Merwin        5.638009       13.282890        0.363003
18         Karen Bern        9.334938        5.845310        0.614540
19       Khloe Miller       10.023810        0.504243        9.486180
20        Seth Vernon       10.859885        0.654033        2.780880
21  Elizabeth Moffitt       12.244927        0.083874       19.224688
22       Eugene Moren       12.247047        1.700349        3.140803
23         Ross Baird       15.476440       30.421115        1.327035
24       Tony Chapman       18.174349        4.417224        0.202211
25     Alice McCarthy       27.169922        0.322887        0.991422
26        David Smith       48.589761        0.048899        1.490515
27       John Castell       64.250517        1.795463        0.663108

In [335]:
query_varcliente = """
WITH vtas_2015 AS (
  SELECT  "Customer Name" as CN, SUM(Sales2) AS total_sales_2015
  FROM ss1
  WHERE AÑO = '2015'
  GROUP BY "Customer Name"
),
vtas_2016 AS (
  SELECT  "Customer Name" as CN, SUM(Sales2) AS total_sales_2016
  FROM ss1
  WHERE AÑO = '2016'
  GROUP BY "Customer Name"
),
vtas_2017 AS (
  SELECT "Customer Name" as CN, SUM(Sales2) AS total_sales_2017
  FROM ss1
  WHERE AÑO = '2017'
  GROUP BY "Customer Name"
),
vtas_2018 AS (
  SELECT "Customer Name" as CN, SUM(Sales2) AS total_sales_2018
  FROM ss1
  WHERE AÑO = '2018'
  GROUP BY "Customer Name"
),
vtas_final AS (
SELECT vtas_2015.CN, vtas_2015.total_sales_2015, vtas_2016.total_sales_2016, vtas_2017.total_sales_2017, vtas_2018.total_sales_2018
FROM vtas_2015
JOIN vtas_2016 ON vtas_2016.CN = vtas_2015.CN
JOIN vtas_2017 ON vtas_2017.CN = vtas_2015.CN
JOIN vtas_2018 ON vtas_2018.CN = vtas_2015.CN)

SELECT CN,
  ((total_sales_2016-total_sales_2015)/total_sales_2015) AS VARIACION_AÑO1,
  ((total_sales_2017-total_sales_2016)/total_sales_2016) AS VARIACION_AÑO2,
  ((total_sales_2018-total_sales_2017)/total_sales_2017) AS VARIACION_AÑO3
FROM vtas_final
WHERE
((total_sales_2016-total_sales_2015)/total_sales_2015)>1 AND
((total_sales_2017-total_sales_2016)/total_sales_2016)>1 AND
((total_sales_2018-total_sales_2017)/total_sales_2017) >1
ORDER BY VARIACION_AÑO1, VARIACION_AÑO2, VARIACION_AÑO3
"""
varcliente = runQuery(query_varcliente)
varcliente

               CN  VARIACION_AÑO1  VARIACION_AÑO2  VARIACION_AÑO3
0     Ken Brennan        2.457317        1.049971       10.295096
1  Anthony Rawles        5.000000      391.057099        1.879488
2    Eugene Moren       12.247047        1.700349        3.140803
3      Ross Baird       15.476440       30.421115        1.327035

In [340]:
query_varcliente = """
WITH vtas_2015 AS (
  SELECT  State as ST, SUM(Sales2) AS total_sales_2015
  FROM ss1
  WHERE AÑO = '2015'
  GROUP BY State
),
vtas_2016 AS (
  SELECT  State as ST, SUM(Sales2) AS total_sales_2016
  FROM ss1
  WHERE AÑO = '2016'
  GROUP BY State
),
vtas_2017 AS (
  SELECT State as ST, SUM(Sales2) AS total_sales_2017
  FROM ss1
  WHERE AÑO = '2017'
  GROUP BY State
),
vtas_2018 AS (
  SELECT State as ST, SUM(Sales2) AS total_sales_2018
  FROM ss1
  WHERE AÑO = '2018'
  GROUP BY State
),
vtas_final AS (
SELECT vtas_2015.ST , vtas_2015.total_sales_2015, vtas_2016.total_sales_2016, vtas_2017.total_sales_2017, vtas_2018.total_sales_2018
FROM vtas_2015
JOIN vtas_2016 ON vtas_2016.ST= vtas_2015.ST
JOIN vtas_2017 ON vtas_2017.ST= vtas_2015.ST
JOIN vtas_2018 ON vtas_2018.ST = vtas_2015.ST)

SELECT ST,
  ((total_sales_2016-total_sales_2015)/total_sales_2015) AS VARIACION_AÑO1,
  ((total_sales_2017-total_sales_2016)/total_sales_2016) AS VARIACION_AÑO2,
  ((total_sales_2018-total_sales_2017)/total_sales_2017) AS VARIACION_AÑO3
FROM vtas_final
WHERE
((total_sales_2016-total_sales_2015)/total_sales_2015)>0 AND
((total_sales_2017-total_sales_2016)/total_sales_2016)>0 AND
((total_sales_2018-total_sales_2017)/total_sales_2017) >0
ORDER BY VARIACION_AÑO1, VARIACION_AÑO2, VARIACION_AÑO3
"""
varcliente = runQuery(query_varcliente)
varcliente

               ST  VARIACION_AÑO1  VARIACION_AÑO2  VARIACION_AÑO3
0    Pennsylvania        0.071413        0.644470        0.174083
1        Illinois        0.152761        0.317760        0.092395
2  North Carolina        0.179877        0.380887        0.255472
3        Michigan        1.534064        0.112109        1.031649
4        Nebraska        1.707266        3.658131        0.321413
5         Georgia        1.850291        0.130219        0.515560

In [368]:
qquery_varcliente = """
WITH vtas_2015 AS (
  SELECT  State as ST, City, SUM(Sales2) AS total_sales_2015
  FROM ss1
  WHERE AÑO = '2015'
  GROUP BY City
),
vtas_2016 AS (
  SELECT  State as ST,City, SUM(Sales2) AS total_sales_2016
  FROM ss1
  WHERE AÑO = '2016'
  GROUP BY City
),
vtas_2017 AS (
  SELECT State as ST,City, SUM(Sales2) AS total_sales_2017
  FROM ss1
  WHERE AÑO = '2017'
  GROUP BY City
),
vtas_2018 AS (
  SELECT State as ST,City, SUM(Sales2) AS total_sales_2018
  FROM ss1
  WHERE AÑO = '2018'
  GROUP BY City
),
vtas_final AS (
SELECT vtas_2015.ST,vtas_2015.City , vtas_2015.total_sales_2015, vtas_2016.total_sales_2016, vtas_2017.total_sales_2017, vtas_2018.total_sales_2018
FROM vtas_2015
JOIN vtas_2016 ON vtas_2016.City= vtas_2015.City
JOIN vtas_2017 ON vtas_2017.City= vtas_2015.City
JOIN vtas_2018 ON vtas_2018.City = vtas_2015.City)

SELECT ST,City,
  ((total_sales_2016-total_sales_2015)/total_sales_2015) AS VARIACION_AÑO1,
  ((total_sales_2017-total_sales_2016)/total_sales_2016) AS VARIACION_AÑO2,
  ((total_sales_2018-total_sales_2017)/total_sales_2017) AS VARIACION_AÑO3
FROM vtas_final
WHERE
((total_sales_2016-total_sales_2015)/total_sales_2015)>0 AND
((total_sales_2017-total_sales_2016)/total_sales_2016)>0 AND
((total_sales_2018-total_sales_2017)/total_sales_2017) >0
ORDER BY VARIACION_AÑO1, VARIACION_AÑO2, VARIACION_AÑO3
"""
varcliente = runQuery(query_varcliente)
varcliente

              ST          City  VARIACION_AÑO1  VARIACION_AÑO2  VARIACION_AÑO3
0   Pennsylvania  Philadelphia        0.013957        0.661437        0.244965
1  Massachusetts      Franklin        0.190037        0.134088        0.532059
2           Ohio         Akron        1.588564        0.291701        1.342952
3       Illinois        Aurora        2.428272        0.485146        0.587505
4    Mississippi       Jackson        3.154533        0.318720        1.429096
5       Michigan       Detroit        4.895874        1.325785        1.265014
6        Florida       Orlando       12.123758        5.175523        0.991823

In [362]:
query_varcliente = """
WITH vtas_2015 AS (
  SELECT  State as ST, City, SUM(Sales2) AS total_sales_2015
  FROM ss1
  WHERE AÑO = '2015'
  GROUP BY State,City
),
vtas_2016 AS (
  SELECT  State as ST,City, SUM(Sales2) AS total_sales_2016
  FROM ss1
  WHERE AÑO = '2016'
  GROUP BY State,City
),
vtas_2017 AS (
  SELECT State as ST,City, SUM(Sales2) AS total_sales_2017
  FROM ss1
  WHERE AÑO = '2017'
  GROUP BY State,City
),
vtas_2018 AS (
  SELECT State as ST,City, SUM(Sales2) AS total_sales_2018
  FROM ss1
  WHERE AÑO = '2018'
  GROUP BY State,City
),
vtas_final AS (
SELECT vtas_2015.ST,vtas_2015.City , vtas_2015.total_sales_2015, vtas_2016.total_sales_2016, vtas_2017.total_sales_2017, vtas_2018.total_sales_2018
FROM vtas_2015
JOIN vtas_2016 ON vtas_2016.City= vtas_2015.City
JOIN vtas_2017 ON vtas_2017.City= vtas_2015.City
JOIN vtas_2018 ON vtas_2018.City = vtas_2015.City)
,
vtas_final2 AS(
SELECT ST,City,
  ((total_sales_2016-total_sales_2015)/total_sales_2015) AS VARIACION_AÑO1,
  ((total_sales_2017-total_sales_2016)/total_sales_2016) AS VARIACION_AÑO2,
  ((total_sales_2018-total_sales_2017)/total_sales_2017) AS VARIACION_AÑO3
FROM vtas_final
WHERE
((total_sales_2016-total_sales_2015)/total_sales_2015)>0 AND
((total_sales_2017-total_sales_2016)/total_sales_2016)>0 AND
((total_sales_2018-total_sales_2017)/total_sales_2017) >0
ORDER BY VARIACION_AÑO1, VARIACION_AÑO2, VARIACION_AÑO3)
SELECT ST,City,((VARIACION_AÑO1+VARIACION_AÑO2+VARIACION_AÑO3)/3) AS PROM
FROM vtas_final2
ORDER BY PROM DESC
"""
varcliente = runQuery(query_varcliente)
varcliente

             ST         City        PROM
0    California   Long Beach  261.585742
1    California   Long Beach   58.641927
2       Indiana     Columbus   27.149297
3       Indiana     Columbus   20.871667
4       Indiana     Columbus   13.833013
..          ...          ...         ...
111    Virginia  Springfield    0.292563
112    Virginia  Springfield    0.286866
113    Virginia  Springfield    0.286383
114    Virginia  Springfield    0.281624
115    Virginia  Springfield    0.280044

[116 rows x 3 columns]